instem_list = {...
  'multivar_MD1wg_sm_surf_surf_diff_H1'...
  'multivar_MD1wg_sm_surf_surf_diff_H2'...
};
outstem_list = {...
  'distmat_MD1wg_sm_diff_H1'...
  'distmat_MD1wg_sm_diff_H2'...
};
nbatches = 200;

for i=1:length(instem_list)
  instem = instem_list{i};
  outstem = outstem_list{i};
  create_distmat_multivar_diff_batch(instem,outstem,nbatches);
end;

