parms = [];
parms.outstem = 'multivar_MD1wg_sm_surf_data';
parms.measlist = {...
  'thick' 'area' 'sulc'...
  'FA_wm' 'LD_wm' 'TD_wm' 'T2w_wm' 'T1w_wm'...
  'FA_gm' 'LD_gm' 'TD_gm' 'T2w_gm' 'T1w_gm'...
};
parms.instem_list = {...
  'MRI_thick_sm1024_ico4'...
  'MRI_area_sm1024_ico4'...
  'MRI_sulc_sm1024_ico4'...
  'DTI_gwcsurf_FA_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_LD_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_TD_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_T2w_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_T1w_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_FA_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_LD_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_TD_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_T2w_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_T1w_gwcsurf_gm_sm1024_ico4'...
};
parms.info_list = {...
  'MRI_thick_info'...
  'MRI_area_info'...
  'MRI_sulc_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
};
parms.forceflag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

args = mmil_parms2args(parms);
multivar_compile_surf_data(args{:});

