run_create_distmat_multivar_diff_Dg
run_create_distmat_multivar_diff_Dw
run_create_distmat_multivar_diff_Dwg
run_create_distmat_multivar_diff_M
run_create_distmat_multivar_diff_M1

%run_create_distmat_multivar_diff_MD1wg

%run_create_distmat_multivar_diff_MD1wg_gender
%run_create_distmat_multivar_diff_MD1wg_halves
%run_create_distmat_multivar_diff_MD1wg_halves_multi
%run_create_distmat_multivar_diff_MD1wg_sqrt
%run_create_distmat_univar_diff_MD1wg
