parms = [];
parms.outstem = 'multivar_Dw_sm_surf_data';
parms.measlist = {...
  'FA_wm' 'LD_wm' 'TD_wm' 'T2w_wm'...
};
parms.instem_list = {...
  'DTI_gwcsurf_FA_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_LD_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_TD_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_T2w_gwcsurf_wm_sm1024_ico4'...
};
parms.info_list = {...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
};
parms.forceflag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

args = mmil_parms2args(parms);
multivar_compile_surf_data(args{:});

