parms = [];
parms.outstem = 'multivar_Dg_sm_surf_data';
parms.measlist = {...
  'FA_gm' 'LD_gm' 'TD_gm' 'T2w_gm'...
};
parms.instem_list = {...
  'DTI_gwcsurf_FA_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_LD_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_TD_gwcsurf_gm_sm1024_ico4'...
  'DTI_gwcsurf_T2w_gwcsurf_gm_sm1024_ico4'...
};
parms.info_list = {...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
};
parms.forceflag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

args = mmil_parms2args(parms);
multivar_compile_surf_data(args{:});

