parms = [];
parms.outstem = 'multivar_M1_sm_surf_data';
parms.measlist = {...
  'thick' 'area' 'sulc'...
  'T1w_wm' 'T1w_gm'...
};
parms.instem_list = {...
  'MRI_thick_sm1024_ico4'...
  'MRI_area_sm1024_ico4'...
  'MRI_sulc_sm1024_ico4'...
  'DTI_gwcsurf_T1w_gwcsurf_wm_sm1024_ico4'...
  'DTI_gwcsurf_T1w_gwcsurf_gm_sm1024_ico4'...
};
parms.info_list = {...
  'MRI_thick_info'...
  'MRI_area_info'...
  'MRI_sulc_info'...
  'DTI_gwcsurf_info'...
  'DTI_gwcsurf_info'...
};
parms.forceflag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

args = mmil_parms2args(parms);
multivar_compile_surf_data(args{:});

