parms = [];
parms.outstem = 'multivar_M_sm_surf_data';
parms.measlist = {...
  'thick' 'area' 'sulc'...
};
parms.instem_list = {...
  'MRI_thick_sm1024_ico4'...
  'MRI_area_sm1024_ico4'...
  'MRI_sulc_sm1024_ico4'...
};
parms.info_list = {...
  'MRI_thick_info'...
  'MRI_area_info'...
  'MRI_sulc_info'...
};
parms.forceflag = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

args = mmil_parms2args(parms);
multivar_compile_surf_data(args{:});

